### ISSUE TITLE
Restrict force of Default Group to ...

### ISSUE THREAD

**Issue by fluffig** [Stibila/defaultgroup#1]
Hi, thanks for this great app. It is nearly exactly what I was looking for. 
Would it be possible to implement some restrictions, so admins or users in special groups do NOT get automatically added to that default group?
In my use case I have a special group that is excluded from sharing (they only receive shares) and every new user must be added to that group. If a new user shall be able to create shares, he is to be deleted from that group and added to another group. It would break my "acl" if every user is added to that group after login.
Thanks
Ben

**Comment by Stibila** [comment]
I'll look into it

**Comment by Stibila** [comment]
New release do what you asked for. You can select groups that will be ignored on login.
Also login hook is now optional and disabled by default so check your settings after update.

**Comment by fluffig** [comment]
Great! Works as expected and even better! Thank you so much!
